[tools]
go = "latest"
node = "lts"
python = "prefix:3.14"
ruby = "latest"
rust = "latest"
zig = "latest"

[settings]
idiomatic_version_file_enable_tools = ["ruby"]

[settings.ruby]
compile = true

[env]
RUBY_CONFIGURE_OPTS = "--with-gmp --with-jemalloc"
